### ISSUE TITLE
Trouble-shooting No Output

### ISSUE THREAD

**Issue by 7Moses** [philipashlock/mediawiki-to-markdown#2]
Hello P,

Thanks for mediawiki-to-markdown,

After installing, I ran the below:

mosesmoses:mediawiki-to-markdown moses$ php convert.php --filename=TomorrowsHorizons_Blogger-01-01-2015.xml --output=export --format=markdown

Creating output directory export

mosesmoses:mediawiki-to-markdown moses$

The "export" folder was created but no markdown files, not to sure where to start trouble shooting.

Note. In the convert.php file I have,

// require 'vendor/autoload.php';

require '/Users/moses/Composer/vendor/composer/autoload_real.php';

I was initially getting an error finding autoload.php.

Thanks for any guidance.

**Comment by victorklos** [comment]
hi @7Moses, you can use `--output=./export` as a temporary fix, until my pull request is accepted.
